Feature/targets endpoint
Vizzuality/cw-ndc-tracking pull request #15
Opened 2018-04-20 11:24 UTC by agnessa

For the targets endpoint the database part is needed. Therefore:
- `bundle exec rake db:create db:migrate db:seed`

This creates three tables:
- `reports` - a report will be linked to a country / user at a later stage when accounts are in place; right now a default report is created by seeds and instantiated with defaults for testing purposes
- `categories` - categories present in this table (linked by slug) are active for a report
- `targets` - for now only generic targets, no support for user-defined ones

Adds an endpoint to fetch targets for category:
`GET /api/v1/sections/planning/categories/ndc_targets/targets?year=2018`

Documentation of the endpoint in docs.

2018-04-23 16:00 UTC, weberjavi approved these changes
From a non Rails savvy perspective every thing looks good to me 😀 
Feel free to merge the PR.

2018-04-23 16:00 UTC, weberjavi commented on app/services/merge_static_and_dynamic_targets.rb
> +      target_hash[:reported_percentage] = 0 # TODO:
Not sure if the `reported_percentage` attribute is needed on targets under the `Planning` section.  
Beyond that everything is working fine :-)

2018-04-24 09:37 UTC, Bluesmile82 commented
The endpoint:
localhost:3000/api/v1/sections?includes[]=categories&includes[]=targets
Doesn't seem to show the targets even if there are some for ndc_targets. Could you please check that?

2018-04-24 09:44 UTC, Bluesmile82 requested changes
Check my comment but great work!

2018-04-26 10:49 UTC, agnessa commented
@Bluesmile82 thank you for your comment, I have a feeling that this might happen when some temporary initialisation happens in the wrong order, e.g. when you try the endpoint before running the seeds, and you end up with more than one report object where one is initialised and the other empty. Could you try `bundle exec rake db:seeds` again - I guess it will fix it in your db. The problem here is we don't have yet the user - report relationships in place so there's some temporary mock ups in place that will be deleted as we keep integrating, so probably it's not bullet proof at it is.

2018-04-26 11:16 UTC, Bluesmile82 approved these changes

2018-04-26 11:17 UTC, merged