Feature/add search bars
Vizzuality/cw-ndc-tracking pull request #39
Opened 2018-07-18 12:09 UTC by weberjavi

This PR adds some missing search boxes according to latest designs
[Pivotal](https://www.pivotaltracker.com/story/show/158943468)
[Basecamp](https://basecamp.com/1756858/projects/13795275/todos/352469981)
[Designs](https://zpl.io/aN4747d)

Extra: 
-  Adds `Add target` button on `NDC targets` and `User defined targets` under `Planning` section. (the functionality is not yet implemented)
-  Updates search box placeholder text with category name.

![image](https://user-images.githubusercontent.com/6906348/42880302-18ac9fce-8a94-11e8-8171-84620e871875.png)

2018-07-19 13:55 UTC, weberjavi commented
@Bluesmile82 do not forget about this ☝️
 😄

2018-07-19 14:31 UTC, Bluesmile82 requested changes
Thanks! But I think the button shouldn't be enabled until it works

2018-07-19 14:31 UTC, Bluesmile82 commented on app/javascript/app/pages/planning/planning-component.jsx
> +              {hasAddTarget && (
Could we disable this button until we have the functionality ready?

2018-07-20 09:17 UTC, weberjavi commented
@Bluesmile82 changes addressed 
Also added a polyfill to support fetch on explorer
[pivotal](https://www.pivotaltracker.com/story/show/159176120)

2018-07-20 09:28 UTC, Bluesmile82 approved these changes
Thanks for the changes and the IE fixing 🥇

2018-07-20 09:54 UTC, merged