Feature/logout
Vizzuality/cw-ndc-tracking pull request #41
Opened 2018-07-23 18:13 UTC by Bluesmile82

This PR adds a provisional logout button to the navbar and makes it work.

- Add Logout action
- Delete LocalStore token and redirect to login on logout

![image](https://user-images.githubusercontent.com/9701591/43095018-cface606-8eb4-11e8-8103-9996267d69a4.png)

Extra:

- Trigger login action on enter when on login form

2018-07-24 12:05 UTC, Bluesmile82 commented
WIP - We have to log out from rails as well as removing the token

2018-07-24 14:58 UTC, Bluesmile82 commented
Ready again

2018-07-25 11:18 UTC, j8seangel requested changes
Please review the comments, thanks!

2018-07-25 11:18 UTC, j8seangel commented on app/javascript/app/components/nav/nav.js
> +import { logout } from '../../services/login.service';
could you change relative imports for absolute? 
as we already have the aliases it will be more readable and maintainable

2018-07-25 11:18 UTC, j8seangel commented on app/javascript/app/components/nav/nav.js
> +    const actions = [
Having this in the render we are generating a new array each time, couldn't we create in the constructor or static property?

2018-07-25 11:18 UTC, j8seangel commented on app/javascript/app/pages/login/login-actions.js
> +export const navigateToLogin = () => ({ type: LOGIN });
We can do the same using redux-tools following the same project structure.
For example: 
```
const navigateToLogin = createAction(LOGIN);
```

2018-07-25 11:18 UTC, j8seangel commented on app/javascript/app/pages/login/login-component.jsx
> +    const handleKeyUp = e => {
Same than before, defining functions on the render lifecycle doesn't sound good.

2018-07-25 14:31 UTC, Bluesmile82 commented
I have addressed the changes. I don't think using createActions is very useful for navigation actions as they are already processed by redux first router but it was very handy for the setUser action

2018-07-25 15:37 UTC, j8seangel commented
I don't think so because at the end the method [createAction](https://redux-actions.js.org/api/createaction) is just a shortcut to avoid typing the `{type: ACTION_TYPE, payload....}` as we have been doing in the rest of the app.

2018-07-25 15:37 UTC, j8seangel approved these changes

2018-07-25 16:02 UTC, merged