Feature/categories endpoints
Vizzuality/cw-ndc-tracking pull request #9
Opened 2018-04-18 10:28 UTC by agnessa

Adds collection and member GET endpoints for categories:

- `GET /api/v1/sections/:section_slug/categories`
- `GET /api/v1/sections/:section_slug/categories/:slug`

Description in docs.

2018-04-18 10:46 UTC, agnessa commented
Sorry not ready yet!

2018-04-19 13:50 UTC, Bluesmile82 requested changes
Please check the not found response. The rest is nice!

2018-04-19 13:50 UTC, Bluesmile82 commented on app/controllers/api/v1/categories_controller.rb
> +        render status: :not_found and return unless @section
I'm getting a missing template error when the section is not found

2018-04-20 08:40 UTC, agnessa commented
Not found responses sorted.

2018-04-20 09:14 UTC, Bluesmile82 approved these changes

2018-04-20 11:15 UTC, merged